import "@hotwired/turbo-rails"
import "./controllers"
import "./jquery.js"
import * as bootstrap from "bootstrap"
import "./charts.js"
import "select2"
import "./webpush.js"
import "./download_pdf.js"
